apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: roboshop
  labels:
    app: nginx
    env: dta
    tier: web-tier
  annotations:
    special: special char and lengthy char can be used and defined. This are mainly used for external resource allocations.

spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: sidecar
      image: busybox
      command: ["/bin/sh", "-c", "while true; do wget -qO- http://localhost; sleep 5; done"]



