apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: roboshop
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: sidecar
      image: busybox
      command: ["/bin/sh", "-c", "while true; do wget -qO- http://localhost; sleep 5; done"]



